// Коды ошибок API. Источник истины — docs/DOMAIN-SHARED.md, раздел 6.
// Новый код сначала добавляется туда, потом сюда.
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  FORBIDDEN = 'FORBIDDEN',
  ORIGIN_FORBIDDEN = 'ORIGIN_FORBIDDEN',
  USER_BLOCKED = 'USER_BLOCKED',
  COURSE_NOT_PURCHASED = 'COURSE_NOT_PURCHASED',
  LESSON_LOCKED = 'LESSON_LOCKED',
  SOLUTION_LOCKED = 'SOLUTION_LOCKED',
  NOT_FOUND = 'NOT_FOUND',
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  HAS_SUBMISSIONS = 'HAS_SUBMISSIONS',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  TOKEN_INVALID = 'TOKEN_INVALID',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
